### ISSUE TITLE
Feature Request: Support typed field selection 

### ISSUE THREAD

**Issue by JonoPrest** [enviodev/hypersync-client-node#12]
Currently field selection is just strings. It would be better if this was a union type of the possible values.

```ts
export interface FieldSelection {
  block?: Array<string>
  transaction?: Array<string>
  log?: Array<string>
}
```

**Comment by joker22008** [comment]
0x9f5f49108338594f2801409ff3a54755c193d621

**Comment by joker22008** [comment]
> В настоящее время в поле выбираются только строки. Было бы лучше, если бы это был тип объединения возможных значений.
> 
> ```ts
> блокировать { выбор полей интерфейса
>   экспортировать?: Массив<строка>
>   транзакция?: Массив<строка>
>   журнал?: Массив<строка>
> }
> транзакция 0x9f5f49108338594f2801409ff3a54755c193d621

**Comment by joker22008** [comment]
> > В настоящее время в поле выбираются только строки. Было бы лучше, если бы это был тип объединения возможных значений.
> > ```ts
> > <span>интерфейса</span><span>полей</span><span>выбор</span><span>{</span><span>блокировать</span>
> >  экспортировать?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>транзакция</span>?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>журнал</span>?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>}</span><span>транзакция</span><span>0x9f5f49108338594f2801409ff3a54755c193d621</span>    
> >   экспортировать
> >   
> > 
> >  
> > ```

**Comment by joker22008** [comment]
> В настоящее время в поле выбираются только строки. Было бы лучше, если бы это был тип объединения возможных значений.
> 
> ```ts
> блокировать { выбор полей интерфейса
>   экспортировать?: Массив<строка>
>   транзакция?: Массив<строка>
>   журнал?: Массив<строка>
> }
> ```

блокировать { выбор полей интерфейса
  экспортировать?: Массив<строка>
  транзакция?: Массив<строка>
  журнал?: Массив<строка>
<span>интерфейса</span><span>полей</span><span>выбор</span><span>{</span><span>блокировать</span>
 экспортировать?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>транзакция</span>?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>журнал</span>?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>}</span><span>транзакция</span><span>0x9f5f49108338594f2801409ff3a54755c193d621</span>    
  экспортировать

**Comment by joker22008** [comment]
> В настоящее время в поле выбираются только строки. Было бы лучше, если бы это был тип объединения возможных значений.
> 
> ```ts
> экспортировать интерфейса Выбор полей {
>   блокировать?: Массив<строка>
>   транзакция?: Массив<строка>
>   журнал?: Массив<строка>
> }
> <span>интерфейса</span><span>полей</span><span>выбор</span><span>{</span><span>блокировать</span>
 экспортировать?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>транзакция</span>?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>журнал</span>?: <span>Массив</span><span><</span><span>строка</span><span>></span><span>}</span><span>транзакция</span><span>0x9f5f49108338594f2801409ff3a54755c193d621</span>    
  экспортировать
  

 ``
